# Generated by Django 4.1.7 on 2024-02-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car_details',
        ),
    ]
