# Generated by Django 4.1.7 on 2024-02-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_delete_car_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_details',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=15)),
                ('car_make', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=10)),
                ('first_reg', models.IntegerField()),
                ('milage', models.IntegerField(max_length=3)),
                ('fuel', models.CharField(max_length=10)),
                ('eng_size', models.IntegerField(max_length=4)),
                ('power', models.IntegerField(max_length=4)),
                ('gear_box', models.CharField(max_length=10)),
                ('seats', models.IntegerField(max_length=2)),
                ('color', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('desciption', models.CharField(max_length=100)),
            ],
        ),
    ]
