# Generated by Django 5.0.1 on 2024-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_details',
            name='image',
            field=models.ImageField(default='', upload_to='cars'),
        ),
        migrations.AddField(
            model_name='car_details',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='car_details',
            name='eng_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car_details',
            name='milage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car_details',
            name='power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car_details',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
