# Generated by Django 5.0.1 on 2024-03-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_details_image_car_details_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_details',
            name='desciption',
            field=models.CharField(max_length=1000),
        ),
    ]
